---
depends_on: null
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: test
steps:
- commands:
  - make test
  depends_on: []
  entrypoint: null
  environment: {}
  image: us.gcr.io/kubernetes-dev/carbonapi/test-runner:latest
  name: run tests
  settings: {}
trigger:
  branch:
  - main
  event:
    include:
    - pull_request
    - push
type: docker
---
get:
  name: .dockerconfigjson
  path: secret/data/common/gcr
kind: secret
name: dockerconfigjson
---
get:
  name: pat
  path: infra/data/ci/github/grafanabot
kind: secret
name: gh_token
---
get:
  name: service-account
  path: infra/data/ci/gcr-admin
kind: secret
name: gcr_admin
---
get:
  name: token
  path: infra/data/ci/argo-workflows/trigger-service-account
kind: secret
name: argo_token
---
kind: signature
hmac: c984b997a9fc1086bf48af43cc1f38122e8317a43066266029ee5d37c7f00541

...
