---
depends_on: null
kind: pipeline
name: test
steps:
- commands:
  - make test
  depends_on: []
  entrypoint: null
  environment: {}
  image: us.gcr.io/kubernetes-dev/carbonapi/test-runner:latest
  name: run tests
  settings: {}
trigger:
  branch:
  - main
  event:
    include:
    - pull_request
    - push
type: docker
---
kind: signature
hmac: 66f18f3ed0af746b72e57f0d70f7df18fcae66a11370644a937e69bbd7cecf56

...
