---
depends_on: null
kind: pipeline
name: test
steps:
- commands:
  - make test
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:alpine
  name: run tests
  settings: {}
trigger:
  branch:
  - main
  event:
    include:
    - pull_request
    - push
type: docker
---
kind: signature
hmac: ca619faa1090c02533f418bd3f3c019cf48fa697e6e1067ce788bf2d84a31b13

...
